# Generated by Django 2.1.7 on 2019-03-07 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='MusicPiece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='SheetMusic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='ManyToMany2.Instrument')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='ManyToMany2.MusicPiece')),
            ],
        ),
        migrations.AddField(
            model_name='instrument',
            name='pieces',
            field=models.ManyToManyField(related_name='instruments', through='ManyToMany2.SheetMusic', to='ManyToMany2.MusicPiece'),
        ),
    ]
